### ISSUE TITLE
Should change taskDone to done

### ISSUE THREAD

**Issue by sunfeng90** [nieheyong/HanhandeSpider#2]
Hi, 我Node的版本是7.8,跑你这个的时候，提示taskDone（）不是一个函数

**Comment by nieheyong** [comment]
谢谢反馈！
在node 7.8版本下，我 把 taskDone 改成 done也是不行的。
接着发现Node 7.8 安装的Async库版本是v2.3.0 ,Node 7.6安装的Async库版本是2.1.5。
这应该是Async 新版本库的问题。已经更新了package.json修改了Async库的版本描述。
你更新代码后重新npm install应该可以了。
[本次修改内容](https://github.com/nieheyong/HanhandeSpider/commit/3708f55587b68c4918d2d7f159eb7e7135ab4619)
