### ISSUE TITLE
运行错误提示：SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by sunfeng90** [nieheyong/HanhandeSpider#3]
提示：/Users/frank/Project/NodeProject/HanhandeSpider/app.js:34
        let q = async.queue(async function (url, taskDone) {
                            ^^^^^
SyntaxError: missing ) after argument list

可能是版本的问题，导致代码出错

**Comment by nieheyong** [comment]
我用的Node.js v7.8删掉之前的Node_Module文件夹然后重新运行npm install 再跑，没有提示你这个错误，无法重现你的问题。你自己能尝试解决一下吗？

**Comment by tuntuntutu** [comment]
比如一页24张专辑，会卡在18张不执行了

**Comment by sunfeng90** [comment]
我利用LZ的方法成功解决了，可能是你网络的问题。重新试一下就好了！

**Comment by tuntuntutu** [comment]
我每次都能重现，设置48就会卡在30几，前面24就会很快

**Comment by DonyZ-V** [comment]
$ node app
E:\Repositories\hanhandeSpider\app.js:34
        let q = asyncQuene(async function ( url, taskDone) {
                           ^^^^^
SyntaxError: missing ) after argument list

这个实在没找到，作者能看看么

**Comment by nieheyong** [comment]
@DonyZ-V  @sunfeng90 
 async 这个关键字到 Node.js 7.6才能使用
在命令行输入
```
node -v
```
检查版本是不是低于Node.js 7.6版本。
如果是，请去 [官网](https://nodejs.org/zh-cn/)下载高于7.6版本的Node.js
